# UDO 거버넌스 설정 파일 스키마
# 프로젝트 루트에 .governance.yaml로 저장

# 버전 (규칙 호환성 확인용)
version: "1.0.0"

# 프로젝트 정보
project:
  name: "UDO-Development-Platform"
  type: "platform"  # platform, web, api, cli, library
  size: "standard"  # nano, minimal, standard, enterprise

# 규칙 설정
rules:
  # 엄격 모드 (true: 모든 규칙 강제, false: 경고만)
  strict_mode: true

  # 스킵할 규칙 (유연성 제공)
  skip_rules: []
  # 예시:
  #   - formatting
  #   - complexity
  #   - docstring

  # 커스텀 규칙 추가
  custom_rules: []
  # 예시:
  #   - scripts/my_custom_rule.py

# 언어별 설정
languages:
  python:
    enabled: true
    version: "3.13"
    formatter: "black"
    linter: "flake8"
    type_checker: "mypy"
    max_line_length: 127
    max_complexity: 10

  typescript:
    enabled: true
    version: "5.x"
    formatter: "prettier"  # 선택적
    linter: "eslint"
    strict_mode: true

# Git 설정
git:
  branch_protection:
    main: true
    develop: true
  commit_format: "conventional"  # <scope>: <message>
  require_signed_commits: false

# 테스트 설정
testing:
  backend:
    framework: "pytest"
    coverage_target: 80
    required: true
  frontend:
    framework: "playwright"
    required: false

# 문서화 설정
documentation:
  require_readme: true
  require_claude_md: true
  require_agents_md: true
  auto_sync_obsidian: true
  # Override with OBSIDIAN_VAULT_PATH env var (recommended)
  obsidian_vault_path: "${OBSIDIAN_VAULT_PATH:-~/Documents/Obsidian Vault}"

# 불확실성 관리
uncertainty:
  enabled: true
  monitor_frequency: "daily"  # daily, weekly, manual
  alert_threshold: 50  # 50% 초과 시 경고

# CI/CD 설정
ci_cd:
  provider: "github-actions"
  run_on_pr: true
  run_on_push: true
  nightly_tests: true

# 자동 업데이트
auto_update:
  enabled: true
  frequency: "weekly"  # weekly, monthly, manual
  version_policy: "minor"  # major, minor, patch
