#!/usr/bin/env python3
"""
Install Documentation Hooks
===========================
Installs git hooks for documentation validation.

Usage:
    python scripts/install_doc_hooks.py [--uninstall]
"""

import os
import sys
import stat
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
GIT_HOOKS_DIR = PROJECT_ROOT / ".git" / "hooks"

PRE_COMMIT_HOOK = """#!/bin/bash
# Documentation Structure Validation Hook
# Auto-generated by install_doc_hooks.py

echo "Running documentation validation..."

# Check if any docs were modified
DOCS_CHANGED=$(git diff --cached --name-only | grep "^docs/" | head -1)

if [ -n "$DOCS_CHANGED" ]; then
    echo "Documentation files changed, validating structure..."

    # Run Python validator
    if command -v python &> /dev/null; then
        python scripts/check_doc_structure.py
        RESULT=$?

        if [ $RESULT -ne 0 ]; then
            echo ""
            echo "Documentation validation FAILED!"
            echo "Please fix the issues above before committing."
            echo ""
            echo "To bypass (not recommended): git commit --no-verify"
            exit 1
        fi
    else
        echo "Python not found, skipping doc validation"
    fi
fi

# Continue with other hooks if they exist
if [ -f .git/hooks/pre-commit.local ]; then
    .git/hooks/pre-commit.local
fi

exit 0
"""

POST_COMMIT_HOOK = """#!/bin/bash
# Session Checkpoint Hook
# Auto-generated by install_doc_hooks.py

# Auto-checkpoint every commit
if command -v python &> /dev/null; then
    COMMIT_MSG=$(git log -1 --pretty=%B)
    python scripts/session_automation.py checkpoint --notes "Commit: ${COMMIT_MSG:0:50}" 2>/dev/null || true
fi
"""


def install_hooks():
    """Install git hooks."""
    if not GIT_HOOKS_DIR.exists():
        print(f"Error: Git hooks directory not found: {GIT_HOOKS_DIR}")
        print("Are you in a git repository?")
        return False

    # Install pre-commit hook
    pre_commit_path = GIT_HOOKS_DIR / "pre-commit"

    # Backup existing hook
    if pre_commit_path.exists():
        backup_path = GIT_HOOKS_DIR / "pre-commit.backup"
        print(f"Backing up existing pre-commit hook to {backup_path}")
        pre_commit_path.rename(backup_path)

    pre_commit_path.write_text(PRE_COMMIT_HOOK, encoding="utf-8")
    os.chmod(pre_commit_path, os.stat(pre_commit_path).st_mode | stat.S_IEXEC)
    print(f"Installed: {pre_commit_path}")

    # Install post-commit hook
    post_commit_path = GIT_HOOKS_DIR / "post-commit"

    if post_commit_path.exists():
        backup_path = GIT_HOOKS_DIR / "post-commit.backup"
        print(f"Backing up existing post-commit hook to {backup_path}")
        post_commit_path.rename(backup_path)

    post_commit_path.write_text(POST_COMMIT_HOOK, encoding="utf-8")
    os.chmod(post_commit_path, os.stat(post_commit_path).st_mode | stat.S_IEXEC)
    print(f"Installed: {post_commit_path}")

    print("\nHooks installed successfully!")
    print("\nFeatures enabled:")
    print("  - Pre-commit: Documentation structure validation")
    print("  - Post-commit: Auto session checkpoint")

    return True


def uninstall_hooks():
    """Remove installed hooks."""
    for hook_name in ["pre-commit", "post-commit"]:
        hook_path = GIT_HOOKS_DIR / hook_name
        backup_path = GIT_HOOKS_DIR / f"{hook_name}.backup"

        if hook_path.exists():
            hook_path.unlink()
            print(f"Removed: {hook_path}")

        if backup_path.exists():
            backup_path.rename(hook_path)
            print(f"Restored: {hook_path} from backup")

    print("\nHooks uninstalled.")


def main():
    if "--uninstall" in sys.argv:
        uninstall_hooks()
    else:
        install_hooks()


if __name__ == "__main__":
    main()
